@baseUrl = http://[::1]:3353
@AdminToken = {{autenticate_admin.response.body.access_token}}
@CourierToken ={{autenticate_courier.response.body.access_token}}




# @name create_courier
POST {{baseUrl}}/users/courier
Content-Type: application/json

{
    "name": "john doe",
    "email": "john@doe.com", 
    "cpf":"10248392812", 
    "password": "123456",
    "phone": "0392450387",
    "latitude": 1.248291,
    "longitude": 124.45324
}

###

# @name create_admin
POST {{baseUrl}}/users/admin
Content-Type: application/json

{
    "name": "jack doe",
    "email": "jack@doe.com", 
    "cpf":"54376587634", 
    "password": "123456",
    "phone": "0392450387",
    "latitude": 1.248291,
    "longitude": 124.45324
}

###

# @name autenticate_courier
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "cpf": "10248392812",
    "password": "123456"
}

###

# @name autenticate_admin
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "cpf": "54376587634",
    "password": "123456"
}

###

# @name create_package_item
POST {{baseUrl}}/package_item
Content-Type: application/json
Authorization: Bearer {{AdminToken}}

{
    "title": "Package 1",
    "deliveryAddress": "Package Street 01 2845013",
    "recipientId": "9f591dc1-6560-4aa6-add0-68c668ebb49f",
    "status": "IN_TRANSIT"
}

###

# @name list_all-package_items_to_admin
GET {{baseUrl}}/package_item?page=1
Content-Type: application/json
Authorization: Bearer {{CourierToken}}

###


# @name get_package_items_by_id
GET {{baseUrl}}/package_item/24b9333a-1f63-4869-b2fa-bb76af534559
Content-Type: application/json
Authorization: Bearer {{AdminToken}}

###