version: '3.8'

services:
  postgres:
    container_name: fast-feet-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  cache:
    container_name: fast-feet-cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data


volumes:
  pgdata:
